/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as ContactsNewRouteImport } from './routes/contacts/new'
import { Route as ContactsImportRouteImport } from './routes/contacts/import'
import { Route as ContactsIdRouteImport } from './routes/contacts/$id'
import { Route as CompaniesIdRouteImport } from './routes/companies/$id'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as CampaignsIdRouteImport } from './routes/campaigns/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsNewRoute = ContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsImportRoute = ContactsImportRouteImport.update({
  id: '/contacts/import',
  path: '/contacts/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/import': typeof ContactsImportRoute
  '/contacts/new': typeof ContactsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/import': typeof ContactsImportRoute
  '/contacts/new': typeof ContactsNewRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/import': typeof ContactsImportRoute
  '/contacts/new': typeof ContactsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/review'
    | '/settings'
    | '/signup'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/companies/$id'
    | '/contacts/$id'
    | '/contacts/import'
    | '/contacts/new'
    | '/campaigns/'
    | '/companies/'
    | '/contacts/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/review'
    | '/settings'
    | '/signup'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/companies/$id'
    | '/contacts/$id'
    | '/contacts/import'
    | '/contacts/new'
    | '/campaigns'
    | '/companies'
    | '/contacts'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/review'
    | '/settings'
    | '/signup'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/companies/$id'
    | '/contacts/$id'
    | '/contacts/import'
    | '/contacts/new'
    | '/campaigns/'
    | '/companies/'
    | '/contacts/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  ContactsIdRoute: typeof ContactsIdRoute
  ContactsImportRoute: typeof ContactsImportRoute
  ContactsNewRoute: typeof ContactsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/new': {
      id: '/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof ContactsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/import': {
      id: '/contacts/import'
      path: '/contacts/import'
      fullPath: '/contacts/import'
      preLoaderRoute: typeof ContactsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  ContactsIdRoute: ContactsIdRoute,
  ContactsImportRoute: ContactsImportRoute,
  ContactsNewRoute: ContactsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
